version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: secure-notes-app
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/secure_notes
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=90d
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - secure-notes-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=secure_notes
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - secure-notes-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/secure_notes --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongo-express:
    image: mongo-express:1.0.0
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongo
    networks:
      - secure-notes-network

networks:
  secure-notes-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
